---
- hosts:
    - localhost
  connection: local
  become: yes
  roles:
    - console-font
    - docker-ce
    - environment-vars
    - flatpak-packages
    - gnome-shell
    - graphical-apps
    - neovim
    - power-config
    - powerline-go
    - powershell
    - python3-setup
    - remmina
    - yum-packages
